const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const ADD_POST = "ADD_POST";

const LOG_IN_REQUEST = "LOG_IN_REQUEST";
const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
const LOG_IN_FAILURE = "LOG_IN_FAILURE";

module.exports = {
  LOG_IN,
  LOG_OUT,
  ADD_POST,
  LOG_IN_REQUEST,
  LOG_IN_SUCCESS,
  LOG_IN_FAILURE,
};
